### ISSUE TITLE
Can not fetch private layers via client.layers.get

### ISSUE THREAD

**Issue by SPlanzer** [koordinates/python-client#51]
Via `client.layers.get()` I can fetch a public layer. However I can not fetch a private layer.
I have checked my API key and I can fetch private layers outside of the Python client

It appears there are no auth headers attached to the request

```
import koordinates

API_KEY = <API KEY>
DOMAIN =  'www.lris.scinfo.org.nz'
client = koordinates.Client(host=DOMAIN,  token=API_KEY)
id = 118946 # Private
#id = 48076 # Public


layer = client.layers.get(str(id))

print(layer)
```

returns 
```
    layer = client.layers.get(str(id))
  File "/home/planzers/miniconda3/envs/koordinates_api/lib/python3.9/site-packages/koordinates/base.py", line 73, in get
    return self._get(target_url, expand=expand)
  File "/home/planzers/miniconda3/envs/koordinates_api/lib/python3.9/site-packages/koordinates/base.py", line 44, in _get
    r = self.client.request("GET", target_url, headers=headers)
  File "/home/planzers/miniconda3/envs/koordinates_api/lib/python3.9/site-packages/koordinates/client.py", line 151, in request
    r = self._raw_request(method, url, headers, *args, **kwargs)
  File "/home/planzers/miniconda3/envs/koordinates_api/lib/python3.9/site-packages/koordinates/client.py", line 191, in _raw_request
    raise exceptions.ServerError.from_requests_error(e)
koordinates.exceptions.NotFound: 404 Client Error: Not Found for url: https://lris.scinfo.org.nz/services/api/v1/layers/118946/

```

Im am using the 0.7.1 Release

**Comment by olsen232** [comment]
Hi Simon, 

I think the issue is using the domain `www.lris.scinfo.org.nz` instead of `lris.scinfo.org.nz` - the first domain redirects to the second one, but only the second one is appropriate when configuring your koordinates client. During the redirect, the authentication is lost, which explains the weird behaviour you're seeing.
Try again with the `lris.scinfo.org.nz` and let me know if you have any issues.

I'll do some work on improving the client's signalling of what went wrong in this case, since right now the root cause of the issue is not clear from the error messages.

(Same as #52)

**Comment by SPlanzer** [comment]
Thanks @olsen232. I have tested this my end and can confirm this solution works against the current release (0.7.1). 

I see you have made commits to address this issue so will close this. Thank you for this.
