### ISSUE TITLE
Can not create draft

### ISSUE THREAD

**Issue by SPlanzer** [koordinates/python-client#52]
I can not create a version from layer object (Client version 0.7.1). 

I am using the below steps to perform this 

```
import koordinates

API_KEY = '<API_KEY>'
DOMAIN =  'www.lris.scinfo.org.nz'
client = koordinates.Client(host=DOMAIN,  token=API_KEY)
id = 114281 # Public

# GET THE LAYER
layer = client.layers.get(str(id))
print(layer)

# CREATE THE DRAFT
draft =  layer.create_draft_version() # <<< FAILS HERE
print draft
```
The above returns:
```
Exception has occurred: ValueError
Need to deserialize from a dict
  File "/home/planzers/data/temp/debug_koordiantes_client/debug.py", line 14, in <module>
    layer.create_draft_version()
ValueError: Need to deserialize from a dict

``` 
I note I can create a version outside the client. e.g POST https://lris.scinfo.org.nz/services/api/v1/layers/114281/versions/

**Comment by olsen232** [comment]
Hi Simon, 

I think the issue is using the domain `www.lris.scinfo.org.nz` instead of `lris.scinfo.org.nz` - the first domain redirects to the second one, but only the second one is appropriate when configuring your koordinates client. During the redirect, the authentication is lost, which explains the weird behaviour you're seeing.
Try again with the `lris.scinfo.org.nz` and let me know if you have any issues.

I'll do some work on improving the client's signalling of what went wrong in this case, since right now the root cause of the issue is not clear from the error messages.

(Same as #51)

**Comment by SPlanzer** [comment]
Thanks @olsen232. I have tested this my end and can confirm this solution works against the current release (0.7.1). 

I see you have made commits to address this issue so will close this. Thank you for this.
